spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:/data/IMS
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect