spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/IMS?createDatabaseIfNotExist=true
    username: root
    password: postgres
    driver-class-name: com.mysql.cj.jdbc.Driver