app:
  jwt-token-validity: 2592000000
  jwt-secret-token: yd9O-cvXAC-keab2TAB-edYSAF-sdk

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update